Add cache import and FT cluster

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -4,7 +4,7 @@
 #   a specified cluster definition. 
 #
 #   Author:         Brian Vanderwende
-#   Last Revised:   16:46, 13 Dec 2022
+#   Last Revised:   17:53, 13 Dec 2022
 #
 
 set -e
@@ -35,6 +35,16 @@ while [[ $# -gt 0 ]]; do
                 >&2 echo "Error: cannot create production deployment as $my_user"
                 exit 1
             fi
+            ;;
+        -c|--import-cache)
+            cache_path=$2
+
+            if [[ ! -d $cache_path ]]; then
+                >&2 echo "Error: specified cache cannot be found"
+                exit 1
+            fi
+
+            shift
             ;;
         *)
             export NCAR_SYS=$1
@@ -194,16 +204,26 @@ fi
 # Create mirrors and prepare env to generate build_cache binaries
 spack config add "config:install_tree:padded_length:${NCAR_SPACK_PAD_LENGTH:-128}"
 
+function trust_keys {
+    for gpg_key in ${!mirror}/build_cache/_pgp/*.pub; do
+        spack gpg trust $gpg_key
+    done
+}
+
 for mtype in LOCAL GLOBAL; do
     mirror=NCAR_SPACK_MIRROR_${mtype} add_mirror=yes
 
     if [[ -d ${!mirror}/build_cache/_pgp ]]; then
-        for gpg_key in ${!mirror}/build_cache/_pgp/*.pub; do
-            spack gpg trust $gpg_key
-        done
+        trust_keys
     elif [[ $(sed 's/production/GLOBAL/;s/testing/LOCAL/' <<< $NCAR_SPACK_DEPLOY_TYPE) == $mtype ]]; then
-        spack mirror create -d ${!mirror} -a
-        spack gpg publish -d ${!mirror}
+        if [[ -n $cache_path ]]; then
+            echo "Importing existing mirror from $cache_path ..."
+            cp -r $cache_path ${!mirror}
+            trust_keys
+        else
+            spack mirror create -d ${!mirror} -a
+            spack gpg publish -d ${!mirror}
+        fi
     else
         add_mirror=no
     fi
