Fix error buffoonery and add publish lock

diff --git a/clusters/gust/postprocess b/clusters/gust/postprocess
--- a/clusters/gust/postprocess
+++ b/clusters/gust/postprocess
@@ -7,7 +7,7 @@
 # CONFIGURABLES
 compilers="cce gcc nvhpc oneapi"
 mpis="cray-mpich"
-skip_list="cce/13.0.2 cce/14.0.1 craype/2.7.14 craype/2.7.16 perftools-base/21.12.0 cray-libsci/22.06.1.3 cray-libsci/21.08.1.2 cray-pals/1.1.8 cray-pals/1.1.5 cray-mpich/8.1.14 cray-mpich/8.1.17 gcc@8.1.0"
+skip_list="cce/13.0.2 cce/14.0.1 craype/2.7.14 craype/2.7.16 perftools-base/21.12.0 cray-libsci/22.06.1.3 cray-libsci/21.08.1.2 cray-pals/1.1.8 cray-pals/1.1.5 cray-mpich/8.1.14 cray-mpich/8.1.17 gcc/8.1.0"
 cray_network=ofi
 
 # Perform common script setup including environment checks
@@ -31,6 +31,9 @@ while [[ $# -gt 0 ]]; do
             ;;
         -c|--clean)
             spack_flags=--delete-tree
+            ;;
+        -f|--force)
+            force_updates=true
             ;;
     esac
 
@@ -63,6 +66,10 @@ append-path MODULEPATH [ lindex \$mpi_mod_path 0 ]
 
 # Use openfabrics
 setenv CRAYPE_NETWORK_TARGET $cray_network
+
+# Add GPU settings
+setenv CRAY_ACCEL_TARGET nvidia80
+setenv MPICH_GPU_SUPPORT_ENABLED 1
 EOF
 
 if [[ ${libfabric[$mod_version]+a} ]]; then
@@ -132,7 +139,7 @@ function copy_mods {
 
                 for mod_file in $(ls -1 --color=never $mod/*); do
                     if [[ " $skip_list " != *" $mod_file "* ]]; then
-			mod_version=${mod_file##*/}
+                        mod_version=${mod_file##*/}
                         cp $mod_file $mod_path/$mod
 
                         if [[ " $mpis " == *" $mod "* ]]; then
@@ -148,7 +155,7 @@ function copy_mods {
 
             for mod_file in $(ls -1 --color=never $mod/* 2> /dev/null); do
                 if [[ " $skip_list " != *" $mod_file "* ]]; then
-		    mod_version=${mod_file##*/}
+                    mod_version=${mod_file##*/}
                     cp $mod_file $mod_path/$mod
 
                     if [[ " $compilers " == *" $mod "* ]]; then
@@ -255,7 +262,7 @@ if [[ $SPACK_ENV == $NCAR_SPACK_ENV_PUBLIC ]]; then
                 [[ $log_active == 1 ]] && echo "  - cloning ${ncar_utils[$util]} repo"
                 git clone git@github.com:NCAR/${ncar_utils[$util]}.git
             else
-                2>&1 echo "Error: No github repo for $util. Perform manual install and retry!"
+                >&2 echo "Error: No github repo for $util. Perform manual install and retry!"
                 exit 1
             fi
         fi
diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -4,7 +4,7 @@
 #   a specified cluster definition. 
 #
 #   Author:         Brian Vanderwende
-#   Last Revised:   20:07, 26 Aug 2022
+#   Last Revised:   14:48, 27 Aug 2022
 #
 
 set -e
@@ -38,14 +38,14 @@ while [[ $# -gt 0 ]]; do
 done
 
 if [[ -z $NCAR_SYS ]]; then
-2>&1 cat << EOF
+>&2 cat << EOF
 Error:  deployment configuration must be specified!
 Usage:  $0 [--no-pkgs] [-p] CONFIG
 
 EOF
 exit 1
 elif [[ ! -f $NCAR_SPACK_DEPLOY_DIR/clusters/$NCAR_SYS/main.cfg ]]; then
-2>&1 cat << EOF
+>&2 cat << EOF
 Error:  deployment "$NCAR_SYS" not recognized from available options
 
 EOF
@@ -72,8 +72,8 @@ spack_clone_path=$NCAR_SPACK_ROOT_DEPLOYMENT/spack
 
 if [[ $NCAR_SPACK_ROOT != $spack_clone_path ]]; then 
     if [[ -d $NCAR_SPACK_ROOT_DEPLOYMENT ]]; then
-        2>&1 echo "Error:  Existing deployment found at ${NCAR_SPACK_ROOT_DEPLOYMENT}. Will not"
-        2>&1 echo -e "        overwrite. Resolve and rerun this script.\n"
+        >&2 echo "Error:  Existing deployment found at ${NCAR_SPACK_ROOT_DEPLOYMENT}. Will not"
+        >&2 echo -e "        overwrite. Resolve and rerun this script.\n"
         exit 1
     fi
 
@@ -129,7 +129,7 @@ fi
 #
 
 if [[ -d $NCAR_SPACK_ENV_BUILD ]]; then
-2>&1 cat << EOF
+>&2 cat << EOF
 Error:  Existing environment found at ${NCAR_SPACK_ENV_BUILD}. Will not
         overwrite. Resolve and rerun this script.
 
diff --git a/src/env/bin/install_packages b/src/env/bin/install_packages
--- a/src/env/bin/install_packages
+++ b/src/env/bin/install_packages
@@ -113,7 +113,7 @@ function prepare_spec {
     done
 
     if [[ $spec == */%* ]]; then
-        2>&1 echo -e "\nError: spec still contains reference! ($spec)"
+        >&2 echo -e "\nError: spec still contains reference! ($spec)"
         exit 1
     fi
 }
@@ -123,7 +123,7 @@ function check_spec {
         if [[ -n $comp ]]; then
             mpis[$comp]="${mpis[$comp]} ${spec//[[:blank:]]/}"
         else
-            2>&1 echo "Error: cannot install an MPI without setting a compiler!"
+            >&2 echo "Error: cannot install an MPI without setting a compiler!"
             exit 1
         fi
     elif [[ $install_type == compiler ]]; then
@@ -208,7 +208,7 @@ function install_spec {
             -e " Total: " -e " from binary cache" -e " Error: " -e " Warning: " || true)
 
     if [[ ${PIPESTATUS[0]} -ne 0 ]]; then
-        2>&1 echo -e "\nError: install of package $spec failed! Aborting installs ...\n"
+        >&2 echo -e "\nError: install of package $spec failed! Aborting installs ...\n"
         exit 1
     fi
 
diff --git a/src/env/bin/publish b/src/env/bin/publish
--- a/src/env/bin/publish
+++ b/src/env/bin/publish
@@ -16,8 +16,14 @@
 #           shell script. So we must activate in the script!
 #
 #   Author:         Brian Vanderwende
-#   Last Revised:   17:06, 16 Aug 2022
+#   Last Revised:   15:04, 27 Aug 2022
 #
+
+function remove_lock {
+    if [[ $NCAR_SPACK_LOCK_PID ]]; then
+        rm -f $NCAR_SPACK_ENV_BUILD/.publock
+    fi
+}
 
 function create_gitignore {
 cat > $NCAR_SPACK_ENV_PUBLIC/.gitignore << EOF
@@ -71,6 +77,11 @@ EOF
 export my_dir="$( cd "$(dirname "$0")" ; pwd )"
 . $my_dir/tools/init.sh
 
+# Create lockfile to block other actions during publishing
+trap remove_lock EXIT
+export NCAR_SPACK_LOCK_PID=$$
+echo $NCAR_SPACK_LOCK_PID > $NCAR_SPACK_ENV_BUILD/.publock
+
 while [[ $# -gt 0 ]]; do
     case $1 in
         -d|--set-default)
@@ -88,7 +99,7 @@ while [[ $# -gt 0 ]]; do
 done
 
 if [[ -z $commit_msg ]]; then
-2>&1 cat << EOF
+>&2 cat << EOF
 Error:  You must provide a commit message as the only argument to this
         script. Make sure to put the message in quotes.
 
@@ -102,7 +113,7 @@ tsecho "Testing build environment for unconcretized changes"
 conc_test=$(2>&1 taskset -c 0-7 spack concretize)
 
 if [[ -n $conc_test ]] && [[ $conc_test != "==> Updating view at $SPACK_ENV/ncarenv" ]]; then
-2>&1 cat << EOF
+>&2 cat << EOF
 $conc_test
 
 Error:  Modifications to $SPACK_ENV/spack.yaml are not properly installed!
@@ -143,12 +154,12 @@ if [[ -d $NCAR_SPACK_ENV_PUBLIC ]]; then
     local_branch="$(git rev-parse --abbrev-ref HEAD)"
 
     if [[ $(git rev-parse --abbrev-ref HEAD) != $NCAR_SPACK_HOST_VERSION ]]; then
-        2>&1 echo "Error:  Incorrect Git repo branch ($local_branch != $NCAR_SPACK_HOST_VERSION)."
+        >&2 echo "Error:  Incorrect Git repo branch ($local_branch != $NCAR_SPACK_HOST_VERSION)."
         exit 1
     fi
 
     if ! git diff --quiet || ! git diff --cached --quiet; then
-        2>&1 echo -e "Error:  Uncommitted changes in Git repo. Resolve and then retry.\n"
+        >&2 echo -e "Error:  Uncommitted changes in Git repo. Resolve and then retry.\n"
         exit 1
     fi
 
@@ -167,9 +178,9 @@ if [[ -d $NCAR_SPACK_ENV_PUBLIC ]]; then
         local_commit=$(git rev-parse HEAD)
         
         if [[ $remote_commit != $local_commit ]]; then
-            2>&1 echo "Error:  Remote repo $NCAR_SPACK_GITHUB and local repo are not in sync."
-            2>&1 echo "           Remote: $remote_commit"
-            2>&1 echo -e "           Local:  $local_commit\n"
+            >&2 echo "Error:  Remote repo $NCAR_SPACK_GITHUB and local repo are not in sync."
+            >&2 echo "           Remote: $remote_commit"
+            >&2 echo -e "           Local:  $local_commit\n"
             exit 1
         fi
     fi
diff --git a/src/spack/bin/clean_bash b/src/spack/bin/clean_bash
--- a/src/spack/bin/clean_bash
+++ b/src/spack/bin/clean_bash
@@ -5,7 +5,7 @@ my_dir="$( cd "$(dirname "$0")" ; pwd )"
 NCAR_SPACK_ROOT=$(readlink -f $my_dir/..)
 
 if [[ ! -f $NCAR_SPACK_ROOT/bin/spack ]]; then
-    2>&1 echo "Error: script is not installed into a Spack clone"
+    >&2 echo "Error: script is not installed into a Spack clone"
     exit 1
 fi
 
