Preparation for gust 22.10 install

diff --git a/clusters/gust/postprocess b/clusters/gust/postprocess
--- a/clusters/gust/postprocess
+++ b/clusters/gust/postprocess
@@ -11,15 +11,12 @@ cray_network=ofi
 
 # MODULES TO COPY
 core="  craype/2.7.17
-        cce/14.0.2
         cce/14.0.3
         gcc/10.3.0
         gcc/11.2.0
         gcc/12.1.0
-        perftools-base/22.06.0
         perftools-base/22.09.0"
 cdep="  cray-libsci/22.08.1.1
-        cray-mpich/8.1.18
         cray-mpich/8.1.19"
 
 # Perform common script setup including environment checks
@@ -88,6 +85,9 @@ prepend-path LD_LIBRARY_PATH /opt/cray/libfabric/${libfabric[$mod_version]}/lib6
 prepend-path MANPATH /opt/cray/libfabric/${libfabric[$mod_version]}/share/man
 prepend-path PKG_CONFIG_PATH /opt/cray/libfabric/${libfabric[$mod_version]}/lib64/pkgconfig
 EOF
+else
+>&2 echo "Error: no libfabric version set for cray-mpich/$mod_version!"
+exit 1
 fi
 
 if [[ ${pals[$mod_version]+a} ]]; then
@@ -101,18 +101,34 @@ prepend-path PE_PALS_PKGCONFIG_LIBS libpals
 prepend-path PE_PKGCONFIG_PRODUCTS PE_PALS
 set-alias mpirun mpiexec
 EOF
+else
+>&2 echo "Error: no pals version set for cray-mpich/$mod_version!"
+exit 1
+fi
+
+if [[ ${pals[$mod_version]+a} ]]; then
+cat >> $1 << EOF
+
+# PMI support
+set defDir "/opt/cray/pe/pmi/${pmi[$mod_version]}"
+setenv CRAY_PMI_INCLUDE_OPTS "-I$defDir/include"
+setenv CRAY_PMI_POST_LINK_OPTS "-L$defDir/lib"
+prepend-path PKG_CONFIG_PATH $defDir/lib/pkgconfig
+prepend-path PE_PKGCONFIG_PRODUCTS PE_PMI
+prepend-path PE_PMI_PKGCONFIG_LIBS cray-pmi
+prepend-path MANPATH $defDir/man
+prepend-path CRAY_LD_LIBRARY_PATH $defDir/lib
+EOF
+else
+>&2 echo "Error: no pmi version set for cray-mpich/$mod_version!"
+exit 1
 fi
 
 cat >> $1 << EOF
 
 # If wrapper is loaded, make sure mpi wrappers are removed at unload
 if { [ info exists ::env(NCAR_WRAPPER_MPI_PATH) ] } {
-    remove-path PATH $::env(NCAR_WRAPPER_MPI_PATH)
-}
-
-# If ncarcompilers is loaded, reload it to keep forward
-if {[ is-loaded ncarcompilers ]} {
-    always-load ncarcompilers
+    prepend-path PATH $::env(NCAR_WRAPPER_MPI_PATH)
 }
 EOF
 }
@@ -196,8 +212,9 @@ if [[ ! -d $mod_deployment ]] || [[ -n $spack_flags ]]; then
 fi
 
 # Version dictionaries
-declare -A libfabric=( [8.1.18]=1.15.0.0 )
-declare -A pals=( [8.1.18]=1.2.0 )
+declare -A libfabric=( [8.1.18]=1.15.0.0 [8.1.19]=1.15.0.0 )
+declare -A pals=( [8.1.18]=1.2.0 [8.1.19]=1.2.2 )
+declare -A pmi=( [8.1.18]=6.1.3 [8.1.19]=6.1.5 )
 declare -A xpmem=( )
 
 [[ $log_active == 1 ]] && echo "Searching for installed compilers ..."
@@ -258,8 +275,9 @@ ncar_utils[qinteractive]=pbstools
 ncar_utils[qcmd]=pbstools
 ncar_utils[qhist]=qhist
 ncar_utils[gladequota]=gladequota
+ncar_utils[get_local_rank]=mpitools
 
-skip_clone="gladequota"
+skip_clone="gladequota mpitools"
 
 if [[ $SPACK_ENV == $NCAR_SPACK_ENV_PUBLIC ]]; then
     for util in ${!ncar_utils[@]}; do
diff --git a/src/env/bin/publish b/src/env/bin/publish
--- a/src/env/bin/publish
+++ b/src/env/bin/publish
@@ -16,7 +16,7 @@
 #           shell script. So we must activate in the script!
 #
 #   Author:         Brian Vanderwende
-#   Last Revised:   09:35, 01 Sep 2022
+#   Last Revised:   11:21, 11 Oct 2022
 #
 
 function remove_lock {
@@ -59,14 +59,30 @@ git add README.md
 }
 
 function create_manifest {
+spack env deactivate
+spack env activate $NCAR_SPACK_ENV_BUILD
+
 # Create package manifest for new installs
 cat > $1 << EOF
 # New package installs
 # Start time: $start_time
 
 singleton:
-$(echo $new_pkgs | sed 's/- /\n    /g' | tail -n +2)
 EOF
+
+while read spec; do
+    spec_hash=$(spack find --format '{hash}' $spec)
+    use_cache=$(awk -F: -v spec="$spec_hash" '$2 == spec {print $3}' $NCAR_SPACK_ENV_BUILD/.installs)
+
+    if [[ $use_cache == no ]]; then
+        echo "    $spec <cache:no>" >> $1
+    else
+        echo "    $spec" >> $1
+    fi
+done < <(tr -d '-' <<< $new_pkgs)
+
+spack env deactivate
+spack env activate $NCAR_SPACK_ENV_PUBLIC
 }
 
 #
@@ -89,6 +105,11 @@ while [[ $# -gt 0 ]]; do
             ;;
         -f|--force)
             force_commit=true
+            ;;
+        --resume)
+            echo "Danger: You are asking to resume a failed publish."
+            read -e -p "        Are you sure (y/N)? " force_resume
+            force_resume=${force_resume:-N}
             ;;
         *)
             commit_msg="$1"
@@ -159,13 +180,17 @@ if [[ -d $NCAR_SPACK_ENV_PUBLIC ]]; then
     fi
 
     if ! git diff --quiet || ! git diff --cached --quiet; then
-        >&2 echo -e "Error:  Uncommitted changes in Git repo. Resolve and then retry.\n"
-        exit 1
+        if [[ ${force_resume,,} == y* ]]; then
+            tsecho "Uncommited changes in Git repo but proceeding anyway (--resume option enabled)"
+        else
+            >&2 echo -e "Error:  Uncommitted changes in Git repo. Resolve and then retry.\n"
+            exit 1
+        fi
     fi
 
     if cmp $NCAR_SPACK_ENV_BUILD/.prototype/spack.yaml spack.yaml >& /dev/null; then
         if [[ $force_commit == true ]]; then
-            tsecho "No spack.ymal changes but proceeding anyway (--force option enabled)"
+            tsecho "No spack.yaml changes but proceeding anyway (--force option enabled)"
         else
             echo -e "\nNo changes detected from public environment; exiting."
             exit 0
@@ -228,7 +253,7 @@ if [[ -n $rm_pkgs ]]; then
 
     while read -r spec; do
         spack uninstall -y $spec
-    done < <(sed 's/[ ]*- //' <<< $rm_pkgs)
+    done < <(sed 's/[ ]*- //' <<< $rm_pkgs | tac)
 fi
 
 # If there are new packages, install sequentially to ensure determinism
@@ -238,7 +263,7 @@ if [[ -n $new_pkgs ]]; then
     tsecho "Creating manifest and installing cached packages"
     pkg_manifest=$log_dir/manifest.$start_time
     create_manifest $pkg_manifest
-    $my_dir/install_packages --cache-only $pkg_manifest
+    $my_dir/install_packages --prefer-cache $pkg_manifest
 
     # Check that installs completed successfully
     if [[ ${PIPESTATUS[0]} == 1 ]]; then
