Changes to support Spack 0.18.0

diff --git a/src/env/bin/install_packages b/src/env/bin/install_packages
--- a/src/env/bin/install_packages
+++ b/src/env/bin/install_packages
@@ -2,13 +2,11 @@
 
 function usage {
 cat << EOF
-Usage: $0 [-H HOSTFILE] [-j JOBS] [-p JOBS] [MANIFEST]
+Usage: $0 [MANIFEST]
 
 Options
-    -H, --hostfile          a line-by-line file containing hosts to use
-    -j, --jobs-per-host     number of build jobs to run on each host
-    -p, --jobs-per-proc     number of build jobs to run per Spack process/instance
-                            (must be less or equal to jobs per host)
+    -h                      show this help message
+    -j, --buildjobs         number of build jobs to run (otherwise will use env default)
 
 EOF
 exit
@@ -25,31 +23,16 @@ my_host=$(hostname)
 
 # Defaults
 pkg_manifest=$SPACK_ENV/packages.cfg
-jobs_per_host=$(spack config get config | sed -n 's/^[ ]*build_jobs: \(.*\)/\1/p')
-jobs_per_proc=8
-remote_env="NCAR_SPACK_ENV=$SPACK_ENV NCAR_SPACK_STARTUP=$NCAR_SPACK_STARTUP NCAR_SPACK_PYDIR=$NCAR_SPACK_PYDIR"
-
-# See if it's a PBS job and use values
-if [[ -n $PBS_NODEFILE ]]; then
-    jobs_per_host=$NCPUS
-    build_hosts=$(uniq $PBS_NODEFILE | xargs)
-    batch_job=true
-else
-    build_hosts=$(uniq $SPACK_ENV/buildhosts.cfg | xargs)
-fi
+build_jobs=$(spack config get config | sed -n 's/^[ ]*build_jobs: \(.*\)/\1/p')
+unset cache_label
 
 while [[ $# -gt 0 ]]; do
     case $1 in
-        -j|--jobs-per-host)
-            jobs_per_host=$2
-            shift
+        -c|--cache-only)
+            cache_label=" (cached)"
             ;;
-        -p|--jobs-per-proc)
-            jobs_per_proc=$2
-            shift
-            ;;
-        -H|--hostfile)
-            build_hosts=$(uniq $2 | xargs)
+        -j|--buildjobs)
+            build_jobs=$2
             shift
             ;;
         *)
@@ -60,14 +43,7 @@ while [[ $# -gt 0 ]]; do
     shift
 done
 
-if [[ $jobs_per_proc -gt $jobs_per_host ]]; then
-    jobs_per_proc=$jobs_per_host
-    2>&1 echo "Error: jobs per Spack process ($jobs_per_proc) must be <= jobs per host ($jobs_per_host)"
-    exit
-fi
-
-num_hosts=$(wc -w <<< $build_hosts)
-start_time=${NCAR_SPACK_DEPLOY_TIME:-$(date +%y%m%dT%H%M)}
+spec_cmd="spack spec -I -N -t -l -c edges"
 
 if [[ -n $build_jobs ]]; then
     build_cmd="spack install -j $build_jobs"
@@ -75,14 +51,20 @@ else
     build_cmd="spack install"
 fi
 
+if [[ -n $cache_label ]]; then
+    build_cmd="$build_cmd --cache-only"
+fi
+
+# Detect version of system GCC
+sys_gcc=$(gcc -v |& grep "gcc version" | cut -d' ' -f3)
+
 cat << EOF
 
 Start time          = $start_time
 Spack environment   = $SPACK_ENV
 Package manifest    = $pkg_manifest
-Jobs per host       = $jobs_per_host
-Jobs per process    = $jobs_per_proc
-Hosts               = $build_hosts
+Build jobs          = $build_jobs
+System GCC          = gcc@$sys_gcc
 
 Processing install manifest ...
 
@@ -90,8 +72,9 @@ EOF
 
 function prepare_spec {
     declare -g spec="$pkg" comp=${comp:-$install_compiler} mpi=${mpi:-$install_mpi}
-    [[ -n $comp ]] && spec="$(sed "s|%CMP%|%$comp|;t;s|$| %$comp|" <<< "$spec")"
-    [[ -n $mpi ]]  && spec="$(sed "s|%MPI%|^$mpi|;t;s|$| ^$mpi|" <<< "$spec")"
+    [[ -n $comp ]] && spec="$(sed "s|%CMP%|%$comp|g;t;s|$| %$comp|" <<< "$spec")"
+    [[ -n $mpi ]]  && spec="$(sed "s|%MPI%|^$mpi|g;t;s|$| ^$mpi|" <<< "$spec")"
+    spec="$(sed -r "s/%gcc( |$)/%gcc@${sys_gcc}\1/g" <<< "$spec")"
     
     while [[ $spec == *:* ]]; do
         spec_opt="$(sed 's|.*<\([^>]*\)>.*|\1|' <<< "$spec")"
@@ -105,45 +88,46 @@ function prepare_spec {
     done
 }
 
-function add_spec {
+function check_spec {
     if [[ $install_build == false ]]; then
-        tsecho "Skipping spec $PCOL$spec$BCOL$type_msg$DCOL (reason: build=false specified)"
+        tsecho "Skipping spec   $PCOL$spec$BCOL$type_msg$DCOL (reason: build=false specified)"
     else
         skip_spec=false
         set +e
 
-        if [[ -f $my_dir/.cache ]]; then
-            spec_hash=$(grep "^${spec}:" $my_dir/.cache | cut -d: -f2)
+        if [[ -f $SPACK_ENV/.installs ]]; then
+            spec_hash=$(grep "^${spec}:" $SPACK_ENV/.installs | cut -d: -f2)
         fi
 
-        if [[ -n $spec_hash ]] && grep -q $spec_hash $SPACK_ENV/spack.lock; then
-            skip_spec=true
+        if [[ -n $spec_hash ]]; then
+            if grep -q $spec_hash $SPACK_ENV/spack.lock; then
+                skip_spec=true
+            else
+                sed -i "/.*${spec_hash}/d" $SPACK_ENV/.installs
+            fi
         else
             spack_find_out=$(spack find -L $spec)
 
             if [[ $? == 0 ]]; then
-                echo "${spec}:$(tail -n1 <<< $spack_find_out | cut -d' ' -f1)" >> $my_dir/.cache
+                echo "${spec}:$(tail -n1 <<< $spack_find_out | cut -d' ' -f1)" >> $SPACK_ENV/.installs
                 skip_spec=true
-            else
-                sed -i "/.*${spec_hash}/d" $my_dir/.cache
             fi
         fi
 
         set -e
 
         if [[ $skip_spec == true ]]; then
-            tsecho "Skipping spec $PCOL$spec$BCOL$type_msg$DCOL (reason: already installed)"
+            tsecho "Skipping spec   $PCOL$spec$BCOL$type_msg$DCOL (reason: already installed)"
         else
-            # Ensure log directories are present
-            if [[ -z $log_dir ]]; then
-                log_dir=$SPACK_ENV/logs/installs.$start_time
-                mkdir -p $log_dir
+            if [[ -n $install_type ]]; then
+                tsecho "Installing spec $GCOL$spec $BCOL(${install_type})$DCOL$cache_label"
+            else
+                tsecho "Installing spec $GCOL$spec$DCOL$cache_label"
             fi
 
-            tsecho "Adding spec   $GCOL$spec$BCOL$type_msg$DCOL to spack.yaml"
-            spack spec -I -N $spec &>> $log_dir/specs
-            spack add $spec &>> $log_dir/specs
-            new_installs=true
+            log_cmd "$spec_cmd $spec" >> $log_specs
+            $spec_cmd $spec &>> $log_specs
+            install_spec
 
             if [[ $spec == lmod* ]]; then
                 new_lmod=true
@@ -153,59 +137,48 @@ function add_spec {
 
     if [[ $install_type == mpi ]]; then
         if [[ -n $comp ]]; then
-            type_msg=" (MPI)"
-            mpis[$comp]="${mpis[$comp]} ${pkg//[[:blank:]]/}"
+            mpis[$comp]="${mpis[$comp]} ${spec//[[:blank:]]/}"
         else
             2>&1 echo "Error: cannot install an MPI without setting a compiler!"
             exit 1
         fi
     elif [[ $install_type == compiler ]]; then
-        compilers="$compilers ${pkg//[[:blank:]]/}"
-        type_msg=" (compiler)"
+        if [[ $spec == gcc* ]]; then
+            compilers="${spec//[[:blank:]]/} $compilers"
+        else
+            compilers="$compilers ${spec//[[:blank:]]/}"
+        fi
     fi
-    
-    unset type_msg
 }
 
-function start_installs {
-    if [[ $new_installs == true ]]; then
-        tsecho "Concretizing new specs"
-        
-        # Spack might use too many CPUs on logins and get us killed
-        if [[ $batch_job == true ]]; then
-            spack concretize &> /dev/null
-        else
-            taskset -c 0-7 spack concretize &> /dev/null
+function install_spec {
+    # Install the package and view pertinent log information
+    log_cmd "$build_cmd $spec" >> $log_installs
+    $build_cmd $spec |& tee -a $log_installs | stdbuf -oL sed 's/^/   /'    \
+            | (grep -e "Executing phase" -e "Successfully installed"        \
+            -e " Total: " -e " from binary cache" || true)
+
+    if [[ ${PIPESTATUS[0]} -ne 0 ]]; then
+        echo -e "\nError: install of package $spec failed! Aborting installs ...\n"
+        exit 1
+    fi
+
+    # Register the compiler in the YAML file if GCC or vendor module
+    if [[ $install_type == compiler ]]; then
+        if [[ -z $current_comps ]]; then
+            current_comps=$(spack config get compilers | grep spec | cut -d: -f2)
         fi
 
-        tsecho "Installing $1 using $num_hosts hosts"
-        install_jobs=$(sed "s/max/$jobs_per_host/" <<< ${install_jobs:-$jobs_per_proc})
-        SECONDS=0
+        if [[ $current_comps != *${spec//[[:blank:]]/}* ]]; then
+            tsecho "Registering $spec as a compiler in spack.yaml"
 
-        for build_host in $build_hosts; do
-            host_slots=$jobs_per_host hnum=1
-
-            while [[ $host_slots -ge $jobs_per_proc ]]; do
-                tsecho "Starting Spack with $install_jobs build jobs on $build_host"
-                
-                if [[ $build_host == localhost ]] || [[ $build_host == $my_host* ]]; then
-                    $build_cmd &>> $log_dir/${build_host}.p$hnum &
-                else
-                    ssh -n $build_host $remote_env $my_dir/tools/remote_bash $build_cmd &>> $log_dir/${build_host}.p$hnum &
-                fi
-
-                pids="$pids $!"
-                host_slots=$((host_slots - install_jobs)); ((hnum++))
-                sleep 1
-            done
-        done
-
-        echo
-        tail -f $log_dir/*.p* | grep -e "Executing phase" -e "Successfully installed" &
-        tpid=$!; wait $pids; kill $tpid
-        echo
-        tsecho "Installs finished after $SECONDS seconds"
-        unset new_installs
+            if [[ $install_external == module ]]; then
+                module_name=$(cut -d' ' -f1 <<< "${comp/@//}")
+                (module purge; module load $module_name; spack compiler find > /dev/null)
+            else
+                spack compiler add $(spack location -i $comp) > /dev/null
+            fi
+        fi
     fi
 }
 
@@ -239,6 +212,12 @@ function define_items {
 # Pretty colors
 GCOL="\033[1;32m" BCOL="\033[1;34m" PCOL="\033[1;35m" DCOL="\033[0m"
 
+# Ensure log directory exists
+log_dir=$SPACK_ENV/logs
+mkdir -p $log_dir
+log_specs=$log_dir/specs.$start_time
+log_installs=$log_dir/installs.$start_time
+
 # MPI libraries for each compiler
 declare -A mpis
 
@@ -247,27 +226,6 @@ while read pkg; do
         continue
     elif [[ $pkg != *'<'* ]] && [[ $pkg == *:* ]]; then
         # If compilers were added, we need to add GCCs to compiler list
-        if [[ $install_type == compiler ]]; then
-            current_comps=$(spack config get compilers | grep spec | cut -d: -f2)
-            start_installs compilers
-
-            for comp in $compilers; do
-                if [[ $current_comps != *${comp}* ]]; then
-                    tsecho "Registering $comp as a compiler in spack.yaml"
-
-                    if [[ $install_external == module ]]; then
-                        module_name=$(cut -d' ' -f1 <<< "${comp/@//}")
-                        (module purge; module load $module_name; spack compiler find > /dev/null)
-                    else
-                        spack compiler add $(spack location -i $comp) > /dev/null
-                    fi
-                fi
-            done
-        # If previous category had custom number of jobs or post-sync, start installs
-        elif [[ -n $install_jobs ]] || [[ $install_sync == after ]]; then
-            start_installs packages
-        fi
-
         for ivar in ${!install_*}; do
             unset $ivar
         done
@@ -295,7 +253,7 @@ while read pkg; do
                     for mpi in $my_mpis; do
                         check_exclusions $mpi || continue
                         prepare_spec
-                        add_spec
+                        check_spec
                     done
                 done
                 ;;
@@ -304,12 +262,12 @@ while read pkg; do
                 for comp in $my_compilers; do
                     check_exclusions $comp || continue
                     prepare_spec
-                    add_spec
+                    check_spec
                 done
                 ;;
             singleton)
                 prepare_spec
-                add_spec
+                check_spec
                 ;;
             *)
                 echo -e "\n====="
@@ -321,7 +279,8 @@ while read pkg; do
     fi
 done < <(awk 'NF' $pkg_manifest)
 
-start_installs packages
+if [[ $SPACK_ENV == $NCAR_SPACK_ENV_BUILD ]]; then
+    . $my_dir/tools/make_localinit.sh build
+fi
 
-. $my_dir/tools/make_localinit.sh build
 unset new_lmod
diff --git a/src/env/bin/publish b/src/env/bin/publish
--- a/src/env/bin/publish
+++ b/src/env/bin/publish
@@ -16,7 +16,7 @@
 #           shell script. So we must activate in the script!
 #
 #   Author:         Brian Vanderwende
-#   Last Revised:   17:29, 18 May 2022
+#   Last Revised:   16:58, 06 Jun 2022
 #
 
 function create_gitignore {
@@ -29,6 +29,17 @@ opt
 EOF
 
 git add .gitignore
+}
+
+function create_manifest {
+# Create package manifest for new installs
+cat > $1 << EOF
+# New package installs
+# Start time: $start_time
+
+singleton:
+$(sed 's/-/ /' <<< "$new_pkgs")
+EOF
 }
 
 #
@@ -90,11 +101,18 @@ pad_length=$(awk '/padded_length: / {print $2}' $SPACK_ENV/spack.yaml)
 
 tsecho "Converting build spack.yaml for use in public environment"
 cd $SPACK_ENV; mkdir -p .prototype; spack env deactivate
-sed -r "s|^([^/]*).{$pad_length}|\1$SPACK_ROOT/opt/spack/|" spack.yaml > .prototype/spack.yaml
+sed '/  specs:/Q' spack.yaml > .prototype/spack.yaml
+
+if [[ -f $NCAR_SPACK_ENV_PUBLIC/spack.yaml ]]; then
+     sed -n '/  specs:/,$ p' $NCAR_SPACK_ENV_PUBLIC/spack.yaml >> .prototype/spack.yaml
+fi
+
+sed -i -r "s|^([^/]*).{$pad_length}|\1$SPACK_ROOT/opt/spack/|" .prototype/spack.yaml
+sed -i "s|\( *lmod: \)/.*|\1$NCAR_SPACK_MODULEROOT|" .prototype/spack.yaml
+sed -i "/[ ]*view:.*/,/[ ]*root:.*/{s|%VIEWROOT%|$NCAR_SPACK_VIEWROOT|}" .prototype/spack.yaml
 spack env activate .prototype
 spack config remove 'config:install_tree:padded_length' 
-spack config remove 'config:install_tree:root' 
-sed -i "s|\( *lmod: \)/.*|\1$NCAR_SPACK_MODULEROOT|" .prototype/spack.yaml
+spack config remove 'config:install_tree:root'
 spack env deactivate
 
 if [[ -d $NCAR_SPACK_ENV_PUBLIC ]]; then
@@ -132,46 +150,28 @@ mv $NCAR_SPACK_ENV_BUILD/.prototype/spack.yaml $NCAR_SPACK_ENV_PUBLIC/spack.yaml
 
 # Switch to the production environment
 spack env activate $NCAR_SPACK_ENV_PUBLIC
+log_dir=$SPACK_ENV/logs
+mkdir -p $log_dir
 
-# Store concretization results
-mkdir -p logs
-tsecho "Concretizing changes in production environment"
-echo "  -> logging to $SPACK_ENV/logs/concretize"
+# If there are new packages, install sequentially to ensure determinism
+new_pkgs=$(grep -v -f <(sed '1,/  specs:/d' spack.yaml) <(sed '1,/  specs:/d' $NCAR_SPACK_ENV_BUILD/spack.yaml))
 
-cat >> logs/concretize << EOF
+if [[ -n $new_pkgs ]]; then
+    tsecho "Creating manifest and installing cached packages"
+    pkg_manifest=$log_dir/manifest.$start_time
+    create_manifest $pkg_manifest
+    $my_dir/install_packages --cache-only $pkg_manifest
 
-=================================================
-   New packages concretized at $(date)
-=================================================
-
-$(2>&1 taskset -c 0-7 spack concretize)
-
-EOF
-
-# Now install new packages
-tsecho "Installing new packages into public environment"
-echo "  -> logging to $SPACK_ENV/logs/install"
-
-cat >> logs/install << EOF
-
-=================================================
-   New packages installed at $(date)
-=================================================
-
-EOF
-
-spack install --cache-only >> logs/install 2>&1
-
-# Check that installs completed successfully
-if [[ ${PIPESTATUS[0]} == 1 ]]; then
-cat << EOF
-Error:  Spack installations did not complete successfully.
-        Check results in \$SPACK_ENV/logs/install and resolve
-        errors before committing changes to GitHub manually.
-
-EOF
-exit 1
+    # Check that installs completed successfully
+    if [[ ${PIPESTATUS[0]} == 1 ]]; then
+        echo "Error:  Spack installations did not complete successfully."
+        echo "        Resolve errors before committing changes to GitHub manually."
+        exit 1
+    fi
 fi
+
+tsecho "Concretizing other environment changes"
+2>&1 taskset -c 0-7 spack concretize > $log_dir/concretize.$start_time
 
 . $my_dir/tools/make_localinit.sh public
 
