Additional changes for v0.19.0 support

diff --git a/src/env/bin/publish b/src/env/bin/publish
--- a/src/env/bin/publish
+++ b/src/env/bin/publish
@@ -16,7 +16,7 @@
 #           shell script. So we must activate in the script!
 #
 #   Author:         Brian Vanderwende
-#   Last Revised:   22:57, 16 Oct 2022
+#   Last Revised:   08:41, 23 Nov 2022
 #
 
 function remove_lock {
@@ -71,7 +71,13 @@ singleton:
 EOF
 
 while read spec; do
-    spec_hash=$(spack find --format '{hash}' $spec)
+    spec_hash=$(spack find --format '{hash}' $spec 2> /dev/null || true)
+
+    if [[ -z $spec_hash ]]; then
+        >&2 echo "Error: package $spec not found in build environment!"
+        exit 1
+    fi
+
     use_cache=$(awk -F: -v spec="$spec_hash" '$2 == spec {print $3}' $NCAR_SPACK_ENV_BUILD/.installs)
 
     if [[ $use_cache == no ]]; then
@@ -253,7 +259,11 @@ if [[ -n $rm_pkgs ]]; then
     tsecho "Removing packages that have been uninstalled from build"
 
     while read -r spec; do
-        spack uninstall -y $spec
+        if [[ $(spack location -i $spec) == ${NCAR_SPACK_ROOT_DEPLOYMENT}* ]]; then
+            spack uninstall --remove -y $spec
+        else
+            spack remove $spec
+        fi
     done < <(sed 's/[ ]*- //' <<< $rm_pkgs | tac)
 fi
 
